### ISSUE TITLE
Receiving request failed code 401 still 

### ISSUE THREAD

**Issue by koshibb** [bsdz/google-drive-remarkable-sync#26] opened 2022-03-15 21:55 UTC
Not sure what this error is being caused by. Current script in Google is:

`function myFunction() {
  // one time code from https://my.remarkable.com/device/connect/mobile
   let rOneTimeCode = "ONETIMECODE";
   let gdFolderSearchParams = "title = 'Remarkable' and mimeType = 'application/vnd.google-apps.folder'";
   let syncMode = "update";
   RemarkableGoogleDriveSyncLib.syncGoogleDriveWithRemarkableCloud(rOneTimeCode, gdFolderSearchParams, "RM Google Drive", syncMode);
}
`

The error I am receiving is: 

Error:
Exception: Request failed for https://document-storage-production-dot-remarkable-production.appspot.com returned code 401
listDocs	@ Remarkable.gs:113
Synchronizer	@ Synchronizer.gs:103
syncGoogleDriveWithRemarkableCloud	@ Library.gs:11
```

**Comment by bsdz** [comment] 2022-03-16 07:47
HTTP code 401 means Unauthorized. I'm not entirely sure what the issue is but might be worth resetting the authentication credentials as described in the troubleshooting section. Hope that helps.

**Comment by koshibb** [comment] 2022-03-16 18:18
So I've tried resetting it as well as even tried creating a new project, with no luck. So I am not sure what the issue is!

**Comment by bsdz** [comment] 2022-03-16 18:34
Actually I think this is a duplicate of this issue #25. Remarkable team have introduced a new API and it seems to only affect some users so far.

**Closed as completed by bsdz** 2022-03-16 18:34 UTC

**Comment by koshibb** [comment] 2022-03-16 18:42
@bsdz so is there anything users can do that are affected by the issue?
